USE [master]
GO

/****** Object:  Database [Przychodnia]    Script Date: 12.04.2026 19:17:52 ******/
CREATE DATABASE [Przychodnia]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Przychodnia', FILENAME = N'C:\Users\izakg\Przychodnia.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Przychodnia_log', FILENAME = N'C:\Users\izakg\Przychodnia_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Przychodnia].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Przychodnia] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Przychodnia] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Przychodnia] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Przychodnia] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Przychodnia] SET ARITHABORT OFF 
GO

ALTER DATABASE [Przychodnia] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Przychodnia] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Przychodnia] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Przychodnia] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Przychodnia] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Przychodnia] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Przychodnia] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Przychodnia] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Przychodnia] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Przychodnia] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Przychodnia] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Przychodnia] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Przychodnia] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Przychodnia] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Przychodnia] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Przychodnia] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Przychodnia] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Przychodnia] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Przychodnia] SET  MULTI_USER 
GO

ALTER DATABASE [Przychodnia] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Przychodnia] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Przychodnia] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Przychodnia] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Przychodnia] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Przychodnia] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [Przychodnia] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Przychodnia] SET QUERY_STORE = ON
GO

ALTER DATABASE [Przychodnia] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Przychodnia] SET  READ_WRITE 
GO

